---
yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

extends: default

ignore: |
  local-secret/
  .git/
  .gitignore
  .github/
  k8s/apps/secrets/
  k8s/manifests/grafana/

rules:
  line-length:
    max: 350
    level: warning
