apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: deny-latest-image
spec:
  validationActions:
    - Deny
  matchConstraints:
    resourceRules:
      - apiGroups: ['', "apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments", "pods", "daemonsets", "statefulsets"]
  validations:
    - containers:
       message: please do not use ':latest' image
      expression: "object.spec.template.spec.containers.all(c, !c.image.endsWith(':latest'))"

    - init-containers:
        message: please do not use ':latest' image
        expression: "object.initContainers.all(c, !c.image.endsWith(':latest'))"
