apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: exception-cilium-privileged
  namespace: cilium-system
spec:
  policyRefs:
    - name: deny-privileged-mode
      kind: ValidatingPolicy
    - name: deny-privilege-escalation
      kind: ValidatingPolicy

    - name: mutate-secure-context-cronjobs-containers
      kind: MutatingPolicy
    - name: mutate-secure-context-cronjobs-initContainers
      kind: MutatingPolicy
    - name: mutate-secure-context-pods-containers
      kind: MutatingPolicy
    - name: mutate-secure-context-pods-initContainers
      kind: MutatingPolicy
    - name: mutate-secure-context-workloads-containers
      kind: MutatingPolicy
    - name: mutate-secure-context-workloads-initContainers
      kind: MutatingPolicy
  matchConditions:
    - name: is-cilium-service-account
      expression: >
        (has(object.spec.serviceAccountName) && object.spec.serviceAccountName in ['cilium', 'cilium-envoy', 'cilium-operator']) || 
        (has(object.spec.template.spec.serviceAccountName) && object.spec.template.spec.serviceAccountName in ['cilium', 'cilium-envoy', 'cilium-operator'])