apiVersion: policies.kyverno.io/v1alpha1
kind: PolicyException
metadata:
  name: exclude-skipped-deployment
  namespace: default
spec:
  policyRefs:
    - name: deny-allow-privileged-mode
      kind: ValidatingPolicy
  matchConditions:
    - name: is-infra-namespace
      expression: "object.metadata.namespace in ['cilium-system', 'falco']"
      
    - name: is-infra-agent
      expression: "object.metadata.name.startsWith('cilium') || object.metadata.name.startsWith('falco')"