{
 "title": "Kubernetes / Views / Global",
 "description": "This is a modern 'Global View' dashboard for your Kubernetes cluster(s).\r\nMade for kube-prometheus-stack and take advantage of the latest Grafana features (8.x.x).\r\nGitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "resolution", "query": "1m, 2m, 3m, 5m" },
   {
    "name": "service",
    "query": {
     "query": "label_values(machine_cpu_cores, service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU  Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / sum(machine_cpu_cores)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)) / sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(kube_namespace_created)" }
   ]
  },
  {
   "title": "Kubernetes Resource Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(kube_namespace_labels)", "legendFormat": "Namespaces" },
    {
     "expr": "sum(kube_pod_container_status_running)",
     "legendFormat": "Running Pods"
    },
    { "expr": "sum(kube_service_info)", "legendFormat": "Services" },
    { "expr": "sum(kube_endpoint_info)", "legendFormat": "Endpoints" },
    { "expr": "sum(kube_ingress_info)", "legendFormat": "Ingresses" },
    { "expr": "sum(kube_deployment_labels)", "legendFormat": "Deployments" },
    { "expr": "sum(kube_statefulset_labels)", "legendFormat": "Statefulsets" },
    { "expr": "sum(kube_daemonset_labels)", "legendFormat": "Daemonsets" },
    {
     "expr": "sum(kube_persistentvolumeclaim_info)",
     "legendFormat": "Persistent Volume Claims"
    },
    { "expr": "sum(kube_hpa_labels)", "legendFormat": "Horizontal Pod Autoscalers" },
    { "expr": "sum(kube_configmap_info)", "legendFormat": "Configmaps" },
    { "expr": "sum(kube_secret_info)", "legendFormat": "Secrets" },
    { "expr": "sum(kube_networkpolicy_labels)", "legendFormat": "Network Policies" }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(kube_service_info)" }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(kube_pod_container_info)" }
   ]
  },
  {
   "title": "CPU Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes))"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{service=~\"$service\"})"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Cluster CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / sum(machine_cpu_cores)",
     "legendFormat": "CPU usage in %"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)) / sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Memory usage in %"
    }
   ]
  },
  {
   "title": "CPU Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", service=~\"$service\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", service=~\"$service\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Utilization by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", service=~\"$service\"}[$__rate_interval])) by (node) / sum(machine_cpu_cores) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", service=~\"$service\"}) by (node)",
     "legendFormat": "{{ node}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Network Utilization (received/transmited packets)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{service=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{service=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Network Sarutation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{service=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_dropped_total{service=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Network Received by node (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{service=~\"$service\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Network Transmit by node (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{service=~\"$service\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  }
 ]
}