{
 "title": "Falco Overview Dashboard",
 "description": "A high level overview of falco metrics per host.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus" },
   { "name": "PROMETHEUS-DATA-SOURCE", "label": "Prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Detection Hits",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "falcosecurity_falco_rules_matches_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Falco Host Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 20, "x": 2, "y": 9 },
   "targets": [
    {
     "expr": "max by(instance) (falcosecurity_falco_cpu_usage_ratio)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "max by(instance) (falcosecurity_falco_start_timestamp_nanoseconds / 1000000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "falcosecurity_scap_engine_name_info",
     "legendFormat": "{{engine_name}}"
    },
    {
     "expr": "falcosecurity_falco_kernel_release_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 2, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "falcosecurity_falco_cpu_usage_ratio",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "falcosecurity_falco_host_memory_used_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}