---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dns-key
  namespace: network
spec:
  encryptedData:
    token: AgBTevFTAc6XUwGOG11pJh91EinQe+axPzj+Tx6A4cFFc8r9VNg0ybnBUt3LgTI7qJJ8M47Nw8R/IkcPuMyDw526ZhFvddP4Jt8evK3Ffty/gMoj1Dx358fGgLAv1/viJ50sN2ExdabHaQVNPYotfJmyGZBfyjGzxshkGaXtmX6dMNqwKGuc/Zrq+cgkusCsNkd9JUn4pF7w9KgpImm6XYxkrz1fkTYHgV1EivpQ2qeD6SWVCpTgn1b4PgWxKSgD+LHiPEgwtrA9Ys1Hz/RKoxPfbVEK2A6wL8RNPnsVBqmZwt2Tntb61vUPjdo5WuJEMObgRsjIDMT9KPAqzrZWv2GQk4tLqcZqg/W1pjetBYeiPHXwso7YwImieN755cW6jzYh85m3xdcggCBe+F4TXLmHsfBqNuwuqHJjMgPkUDX789p/w5oGgO3e61eQF/4T3QVROumnCfJ9UAcwYYbJ4fZ/gVKxSL8MLfTt940E8apsUh1dQwZeNQtE0TYeEQVGrlvjXZ2AMMz3eieTENn9EY/N5fRpGg2YRdgO1E5bevAqveLYGqw18OLAhvRugnIN5cxSPTh00LArRYZLsloVy1/L8vt/HNbwUBFGYpWPlMT/VuSyXlV2KQzeylYQQU342GWHoi675+7wBpx86Q65O5a5NZOzodnI3OgwZPnezb/vKw8wJwBs/UjIYiSUMwFSyfkj+iWM9EZmvjsOWP4RyBO9q7Jlluy5fjFHjY6I2xYHgqcZHAk=
  template:
    metadata:
      name: dns-key
      namespace: network
    type: Opaque
