---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute #TLSRoute ? se renseigner pour une encryption du début à la fin
metadata:
  name: http-app-nginx
  namespace: nginx
spec:
  parentRefs:
    - name: public-gateway
      namespace: gateway-system
  hostnames:
    - "*.himmel-local.com" # à définir, doit match un hostname dans la gateway ?
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: nginx-service
          port: 80
