---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "l3-rule-test"
  namespace: nginx
spec:
  endpointSelector:
    matchLabels:
      app: nginx
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s-app: cilium-envoy
        - matchLabels:
            io.kubernetes.pod.namespace: nginx
        - matchLabels:
            io.kubernetes.pod.namespace: gateway-system
        - matchLabels:
            io.kubernetes.pod.namespace: prometheus
        - matchLabels:
            io.kubernetes.pod.namespace: alloy
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
