---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "l3-rule-test"
  namespace: nginx
spec:
  endpointSelector:
    matchLabels:
      app: nginx
  ingress:
    ingressDeny:
      fromEntities:
        - world
