---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "l3-rule-test"
  namespace: nginx
spec:
  endpointSelector:
    matchLabels:
      app: nginx
  ingress:
    - fromCIDRSet:
        - 192.168.0.0/16
        - 10.0.0.0/8
        - 172.16.0.0/12
