alertmanager:
  config:
    global:
      resolve_timeout: 5m

    route:
      receiver: email-notification

    receivers:
      - name: "null"

      - name: "email-notification"
        email_configs:
          - to: alexandre.alertmanager@hotmail.fr

      - name: "slack"
        slack_configs:
          - api_url: # à ajouter plus tard /!\ Bitnami Sealed Secrets
            channel: "#alerts"
            send_resolved: true