---
controller:
  type: 'daemonset'

alloy:
  enableReporting: true # sending Grafana Labs anonymous usage stats to help improve Grafana
  stabilityLevel: "generally-available"

  configMap:
    create: true
    content: |
      discovery.kubernetes "pods" {
        role = "pod"
      }

      discovery.relabel "pod_logs" {
        targets = discovery.kubernetes.pods.targets

        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          action        = "replace"
          target_label  = "namespace"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          action        = "replace"
          target_label  = "pod"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          action        = "replace"
          target_label  = "container"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
          action        = "replace"
          target_label  = "app"
        }
      }

      loki.source.kubernetes "pod_logs" {
        targets    = discovery.relabel.pod_logs.output
        forward_to = [loki.process.filter_logs.receiver]
      }

      loki.process "filter_logs" {
        stage.cri {}

        stage.drop {
          source     = ""
          expression = "^\\s*$"
        }

        forward_to = [loki.write.homelab_loki.receiver]
      }

      loki.write "homelab_loki" {
        endpoint {
          url = "http://loki-gateway.loki.svc.cluster.local:3100/loki/api/v1/push"
        }
      }
rbac:
  create: true
