---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public-gateway
  namespace: gateway-system
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "projet-himmel.duckdns.org"
      allowedRoutes:
        namespaces:
          from: All

    - name: https
      protocol: HTTPS
      port: 443
      hostname: "projet-himmel.duckdns.org"
      tls:
        mode: Terminate
        certificateRefs:
          - group: ''
            kind: Secret
            name: himmel-tls-secret
            namespace: cert-manager
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              tier: app
