---
apiVersion: v1
kind: ConfigMap
metadata:
  name: falo-custom-rules
  namespace: falco
data:
  my-rules.yaml: |
    - rule: shell_in_container
      desc: check for any shell activity within a container
      condition: >
        (evt.type in(execve, execveat)) and
        container.id != host and
        (proc.name = bash or
        proc.name = ksh)
      output: >
        shell in a container detected |
        user=%user.name container_id=%container.id container_name=%container.name
        shell=%proc.name parent=%proc.pname cmdline=%proc.cmdline
      priority: ALERT

    - rule: deny_nmap
      desc: deny nmap scan in a container
      condition: >
        (evt.type in (connect)) and
        container.id != host and
        (proc.name = nmap)
      output: >
        Network scan detected |
        user=%user.name container_id=%container.id container_name=%container.name
        shell=%proc.name parent=%proc.pname cmdline=%proc.cmdline
      priority: WARNING

    - rule: read_etc_shadow
      desc: check for any consult of /etc/shadow
      condition: >
        (evt.type in(open, openat)) and
        container.id != host and
        (fd.name == /etc/shadow)
      output: >
        /etc/shadow opened |
        user=%user.name container_id=%container.id  continer_name=%container.name
        path:%fd.name
      priority: WARNING
