---
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "first-pool"
spec:
  allowFirstLastIPs: Yes
  serviceSelector:
    matchLabels:
      announce: active
  blocks:
    - cidr: "192.168.1.192/26"
