---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-whook
  namespace: prometheus
spec:
  encryptedData:
    api_url: AgA1l2q7J3zYm91bNE6We7FztChQOQ7jxFVI8wYBBMUyOkmA+2ODgdmNzbiyZN2OMaS7GliVHrKJDS3AcnIONTBdea1SxypL5UtLx9ioRwuy4UapCHq0SESTitC+o5eUb839P/m0bAGvkrF2svCoKFMgOE+b+CcT85BxkH/+wero+/qGvgFe5LH7z1tlS6oZBZBOIn3sHIfJoNLHUv52zP9yYymHOWN4YrZAA5B7qtpK12agakjlorCdEsZCPruCMklPFbX/HCT555aaLhzkQeT2hdCNNflVGRvO0PDBJDS4WddQWu6eRxkvog5n44kU6q5+8dhNbxG9cOzlajpZs5M+w00JI98Mov7KOePFQph+TP0HWw+KevI7yf6nvGFKOLmR7kKkidWdTYE3/OZaUmDnQlovtUS/c9lBmWMZifz5nomdIhTLF3+gqhCeRpfV3Zx1ZfK4QNuF7tez+pzeMEQDS7JVEZtRE/WDtAXhfb0T7NdZOB99zFhxnY7QeSl+I9KxH9bRJHg1KqDFkepRwuCo4RnWXfu58OeoiF2vHp6Lzhea7JZ61GBIiC8iB2uYnqBMOGzfK5MXVZzZGFWgY9jhCESHPXybzGvaIgNv2XBrHIMNGXhlU8w+p+ccC9Yf4TPbRggo6X9s36d98TizSh0awFIwQq7Cf9tsfsI2gNpAT5dxBLTxghfYHfJV6xhmukfZFZhSlcuIsltFg3vkzihFt0KXPY2YakkUWv8sduVlHrAd1p6HDAMFrIkIPE7bJqD7/3cfAHR6iIOYXrShU7/qLdj+yn8hPmx/Ar4XjUKnc+0=
  template:
    metadata:
      name: slack-whook
      namespace: prometheus
