---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://falcosecurity.github.io/charts"
      chart: falco
      targetRevision: "8.0.2"
      helm:
        valueFiles:
          - $values/k8s/apps/helm-values/falco-values.yaml
        values: |
          json_output: true
          json_include_output_property: false
          metrics:
            enabled: true
            rulesCountersEnabled: true
            interval: 15s
          webserver:
            enabled: true
            prometheus_metrics_enabled: true
            listen_port: 8765
          serviceMonitor:
            create: true
            labels:
              release: prometheus
            interval: 15s

    - repoURL: "https://github.com/Alexandre1609-bit/Projet-Himmel.git"
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
