---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana-community.github.io/helm-charts
    chart: loki
    targetRevision: 17.3.1
    helm:
      values: |
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          storage:
            type: filesystem
            bucketNames:
              chunks: chunks
              ruler: ruler
              admin: admin
            filesystem:
              chunks_directory: /loki/chunks
              rules_directory: /loki/rules
        singleBinary:
          replicas: 1
        persistence:
          enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
