---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana-community.github.io/helm-charts
    chart: loki
    targetRevision: 17.3.1
    helm:
      values: |
        deploymentMode: SingleBinary
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        singleBinary:
          replicas: 1
          persistence:
            enabled: false
        loki:
          auth_enabled: false
          useTestSchema: true
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
            bucketNames:
              chunks: chunks
              ruler: ruler
              admin: admin
        persistence:
          enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
