apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: default
  sources:
    - repoURL: "https://prometheus-community.github.io/helm-charts"
      chart: kube-prometheus-stack
      targetRevision: "83.6.0"
      helm:
        valueFiles:
          - $values/k8s/prometheus-values.yaml

    - repoURL: "https://github.com/Alexandre1609-bit/Projet-Himmel"
      targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true