apiVersion: batch/v1
kind: CronJob
metadata:
  name: duckdns-updater
  namespace: network
spec:
  schedule: "*/15 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: duckdns-curl
              image: curlimages/curl:latest
              env:
                - name: DUCKDNS_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: dns-key
                      key: token
              command:
                - /bin/sh
                - -c
                - "curl -k -s 'https://www.duckdns.org/update?domains=projet-himmel&token=${DUCKDNS_TOKEN}&ip='"
          restartPolicy: OnFailure
